import { Inter, Archivo } from "next/font/google";
import "./globals.scss";

import Header from "./components/header/header";
import Footer from "./components/footer/footer";
import AnimationWrapper from "./components/animationWrapper/animationWrapper";

const inter = Inter({ subsets: ["latin"] });
const archivo = Archivo({ subsets: ["latin"], variable: '--font-archivo' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${archivo.variable}`}>
        <Header />
          <AnimationWrapper>
            {children}
          </AnimationWrapper>
        <Footer />
      </body>
    </html>
  );
}
